### PR TITLE
Don't hardcode PDS namespace

### PR DESCRIPTION
**Pull request by jiri-janousek**
**What this PR does / why we need it**:

If users choose a different namespace, Teleport and Prometheus will follow it but PDS agent would break.

### CODE REVIEW

**Review by holubales — APPROVED** [review]
LGTM. So the agent tag `dev-cf55aca` already understands this env variable and there is no need for a new tag, right?

**Comment by jiri-janousek** [comment]
I cannot update the tag here because of missing RBAC. It is updated in #22.

**Review by osery — APPROVED** [review]
LGTM.

**Comment by holubales** [comment]
> I cannot update the tag here because of missing RBAC. It is updated in #22.

OK, then I don't quite get why are these separated. This change wouldn't work (or to be precise might potentially break under specific circumstances). I understand the need to keep the PRs short and concise but I also see the need to merge PRs that are fully functional (and especially here where every change is currently released as a new version). It's not a big deal now but I don't see this as a good practice. @osery WDYT?

**Comment by jiri-janousek** [comment]
I should have explicitly state this PR is still fully functional as the old pds-agent image won't break by any change in this PR. The old agent image does not care about he namespace yet.

**Comment by osery** [comment]
> > I cannot update the tag here because of missing RBAC. It is updated in #22.
> 
> OK, then I don't quite get why are these separated. This change wouldn't work (or to be precise might potentially break under specific circumstances). I understand the need to keep the PRs short and concise but I also see the need to merge PRs that are fully functional (and especially here where every change is currently released as a new version). It's not a big deal now but I don't see this as a good practice. @osery WDYT?

Tbh, I do like the approach @jiri-janousek is taking. Clear single-purpose PRs that are easy to review, but which still keep everything fully functioning.

**Comment by holubales** [comment]
> Tbh, I do like the approach @jiri-janousek is taking. Clear single-purpose PRs that are easy to review, but which still keep everything fully functioning.

But that's my point. If anyone installs version `0.0.12` with a namespace other than `pds-system`, it wouldn't be functioning. Otherwise, I completely agree with what you said, I'm just not sure that it applies here 100%.

**Comment by osery** [comment]
> But that's my point. If anyone installs version `0.0.12` with a namespace other than `pds-system`, it wouldn't be functioning. Otherwise, I completely agree with what you said, I'm just not sure that it applies here 100%.

Not that I want to nit pick, but this mode wasn't really supported before so it is not like it got broken by this PR, right? :thinking:
I mean, I am glad you keep us honest with how we all work, but tbh I don't see anything wrong on these particular PRs. Yet I totally agree that if these were breaking stuff just to split the PRs that would indeed be undesirable.

**Comment by jiri-janousek** [comment]
I'm sorry that I still haven't explained properly that changes in this PR are fully functional. No change in PDS agent itself is needed.

* If anyone installs version 0.0.12 with a namespace other than pds-system, it will be fully functional. The old agent image does not care about the namespace at all yet.
* If anyone installs version 0.0.11 or a few older versions with a namespace other than pds-system, it will likely not work because pds-agent chart templates (not the agent image) has the pds-system namespace hard-coded.

**Comment by holubales** [comment]
OK, then I'm sorry for making a fuss around this. I see that we are all in agreement and in this particular case I wrongly understood the issue and your (@jiri-janousek) structuring of PRs was perfectly fine. Please do accept my apology.

**Comment by jiri-janousek** [comment]
I really like that you are careful about breaking changes :+1: The misunderstanding arose from my fault to communicate clearly that this is not a breaking change. I apologize for that.

**Pull request merged**
